language: java
jdk:
  - oraclejdk7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_failure:
  - sh -e "cat /home/travis/build/NFLabs/zeppelin/logs/zeppelin*.log"
  - sh -e "cat /home/travis/build/NFLabs/zeppelin/logs/zeppelin*.out"
